// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwSViXg9NshQs07lrbtWLyKTC15ueZ_b4',
    appId: '1:203083341822:web:d908c48b0cb607d7b8aaaf',
    messagingSenderId: '203083341822',
    projectId: 'tgo-test-a9bda',
    authDomain: 'tgo-test-a9bda.firebaseapp.com',
    storageBucket: 'tgo-test-a9bda.appspot.com',
    measurementId: 'G-8R4P74DQK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_VORF6e6AEkrcSby9VMX4_DQcsY_AEA',
    appId: '1:203083341822:android:6f3221f115877aa0b8aaaf',
    messagingSenderId: '203083341822',
    projectId: 'tgo-test-a9bda',
    storageBucket: 'tgo-test-a9bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkPWKczGzZ9NL4JMP6obvVOKdPYp4ryf4',
    appId: '1:203083341822:ios:a1d44c841e0b0b08b8aaaf',
    messagingSenderId: '203083341822',
    projectId: 'tgo-test-a9bda',
    storageBucket: 'tgo-test-a9bda.appspot.com',
    iosClientId: '203083341822-2s8uvuvvgumcm9oepv8terap8a16ddtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tgo-test',
  );
}
